name: Convert URL content to Base64

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch content from URL and update file
        run: |
          # Fetch content from URL
          curl -L "https://raw.githubusercontent.com/Surfboardv2ray/TGParse/main/config-tg.txt" | base64 --encode > ./base64.txt

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update file from URL"
          git push
