name: Parse Channels, Split & Base64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  run_python_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Parser
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'


    - name: Install Parser dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        

    - name: Run Parser
      env:
          THRD_PARS: '128'
          PARS_DP: '2'
          USE_INV_TC: 'n'
      run: |
        python tg-parser.py
          
    - name: Local Authentication
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"

    - name: Commit & push Parser
      run: |
        git add .
        git commit -m "Update files"
        git pull
        git push

    - name: Set up Splitter
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

  
    - name: Split UTF-8 and update subscriptions
      run: |
        python python/splitter.py

    - name: Check for split changes
      id: changes
      run: |
        git diff --quiet && echo 'No changes' || echo '::set-output name=changed::true'

    - name: Commit and push splitted
      if: steps.changes.outputs.changed == 'true'
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add python/vmess python/vless python/trojan python/ss python/socks python/hysteria2 python/hy2 python/tuic
          git commit -am "Update v2ray subscriptions"
          git push

    - name: Convert to base64
      run: |
          content=$(cat configtg.txt | base64| tr -d '\n')
            echo "$content" > splitted/mixed
          for file in python/socks python/ss python/trojan python/vless python/vmess python/tuic python/hysteria2 python/hy2; do
            base64 $file > "splitted/$(basename $file)"
          done
       
    - name: Check for Base64 Changes
      id: changes64
      run: |
            git diff --quiet && echo 'No changes' || echo '::set-output name=changed::true'   
      
    - name: Commit and push Base64
      if: steps.changes.outputs.changed == 'true'   
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add splitted/mixed
          git add splitted/*
          git commit --allow-empty -m "Update output files"
          git push
