name: Run Python script and push changes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_python_and_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Check Git version
      run: git --version
      
    - name: Update Git
      run: |
        sudo add-apt-repository ppa:git-core/ppa -y
        sudo apt-get update
        sudo apt-get install git -y
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install system dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxslt-dev python-dev-is-python3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        

    - name: Run Script
      env:
          THRD_PARS: '128'
          PARS_DP: '2'
          USE_INV_TC: 'n'
      run: |
        python tg-parser.py

      
    - name: Update Output
      run:
        git status
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Update configs"
        git push

